### ISSUE TITLE
Anchor Tags not properly being rendered.

### ISSUE THREAD

**Issue by dreamingbinary** [joeyespo/grip#137] opened 2015-07-10 23:29 UTC
`#### <a name="setup_PHPStorm"></a>`
`#### 7. Setup PHPStorm`

becomes

`<h4>
<a id="user-content--6" class="anchor" href="#-6" aria-hidden="true"><span class="octicon octicon-link"></span></a><a name="user-content-setup_PHPStorm"></a>
</h4>`

`<h4>
<a id="user-content-7-setup-phpstorm" class="anchor" href="#7-setup-phpstorm" aria-hidden="true"><span class="octicon octicon-link"></span></a>7. Setup PHPStorm</h4>`

thereby disallowing clickable menus at the top to jump to #setup_PHPStorm.

**Comment by joeyespo** [comment] 2015-07-15 04:04
Does this work for you when you push to GitHub?

There might be a bug [here](https://github.com/joeyespo/grip/blob/ce39bf43fbd747a54a6d2997ef32bf69764fb446/grip/templates/index.html#L53). That code doesn't account for custom `<a name>` tags.

Otherwise, why not link to `#7-setup-phpstorm` instead of adding your own anchor? Anchors for headers are automatically generated.

**Comment by moll** [comment] 2015-07-17 13:34
Just stumbled upon this after upgrading to v3, too.
I too use custom anchors to not depend on section titles. An example of a failing Markdown doc at https://github.com/moll/js-strange/blob/master/doc/API.md.

**Comment by samreid** [comment] 2015-08-28 04:01
I believe I am suffering from this same problem.  I was using custom anchors as recommended by http://stackoverflow.com/questions/6695439/how-do-you-create-link-to-a-named-anchor-in-multimarkdown so that minor wording changes don't end up breaking URLs.   When I looked at the HTML generated by grip, I saw that my anchors were still there, but prefixed with "user-content".  I might be able to use that, but it will lead to an inconsistency in the links for the GitHub rendered MD vs the Grip rendered MD.

**Comment by samreid** [comment] 2015-08-28 04:06
> In the short-term, why not link to #7-setup-phpstorm instead of adding your own anchor? Anchors for headers are automatically generated.

I'm not seeing the anchors generated for headers when I use:
```
grip --gfm --context=my/context README.md --export index.html
```

I'm using `Grip 3.2.0`

**Comment by samreid** [comment] 2015-08-28 04:10
I updated to grip 3.3.0 (latest according to pip) and am still seeing no anchors generated for headers.  My header code:

```md
# Example 1: Simple Embedding
```

grip generates this html:
```html
<h1>Example 1: Simple Embedding</h1>
```

am I doing this right?

**Comment by joeyespo** [comment] 2015-08-28 04:14
@samreid Try it without `--gfm`. That option makes it render like a GitHub comment or user issue would be rendered (which is not the same thing as a Readme file).

**Comment by joeyespo** [comment] 2015-08-28 04:14
@samreid And thanks for providing all that info!

**Comment by samreid** [comment] 2015-08-28 05:57
Ah, thanks for explaining the `--gfm`, I tried running without it and got an anchorable html header:

```html
<h1>
<a id="user-content-example-1-simple-embedding" class="anchor" href="#example-1-simple-embedding" aria-hidden="true"><span class="octicon octicon-link"></span></a>Example 1: Simple Embedding</h1>
```

I'll move forward with that, thanks @joeyespo!

**Comment by joeyespo** [comment] 2015-08-28 15:58
Perfect! Glad that helped.

@dreamingbinary Could this help you too?

(Side note: Problems caused by using `--gfm` seems to be propping up all over. I wonder if that should be renamed to be more clear. The name came from the GitHub API, but that certainly doesn't need to be the same.)

**Comment by joeyespo** [comment] 2015-11-19 08:12
Closing this. I'm assuming `--gfm` was causing confusion. That argument was renamed to `--user-content` in v4.0.0. Feel free to re-open if you still have a problem!

**Closed by joeyespo** 2015-11-19 08:12 UTC

**Comment by blah238** [comment] 2016-06-16 22:44
I am using `grip 4.2.0` without the `--user-content` command line and still seeing my anchor links being parsed incorrectly (`<a name="my-anchor-link"></a>` becomes `<a name="user-content-my-anchor-link"></a>`). Am I misunderstanding something? How do I do this?

**Comment by Sharon-L** [comment] 2017-06-28 11:19
I had a similar issue with Grip v4.3.2 and Python v2.7.13, whereby internal links to<code><a&nbsp;name="ANCHOR"></a></code> anchors did not work (despite displaying correct URLs). The same links worked well in GitHub.  
I was able to resolve this by replacing the `name` attribute in the <a> tag with the `id` attribute —
<code><a&nbsp;id="ANCHOR"></a></code>.

**Comment by tupm20154207** [comment] 2018-07-11 09:30
I'm currently on grip 4.5.2 and still having the same problem as you guys. Can someone tell me how to fix this?

**Comment by signalogic** [comment] 2019-04-19 19:29
I modified my custom anchors (using them for clickable menus), but in addition to adding the "user-content-" prefix the link must be scrubbed of all uppercase chars.  The anchor tag itself can be unchanged.  This is working for all browser versions, including older XP stuff.

Linking to headers sounds good in theory, but seems to me Github is unpredictable in what HTML and css versions they support for Markdown, so that would be unreliable.  This is not the first time we've had to insert manual links, it happened with images being found thru Google image search also.
