### ISSUE TITLE
Grip doesn't render GFM checkbox lists

### ISSUE THREAD

**Issue by daveyarwood** [joeyespo/grip#112] opened 2015-04-01 19:15 UTC
More information: https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments
Example: https://github.com/colepanike/Formicidae/blob/master/TODO.md

**Comment by joeyespo** [comment] 2015-04-01 19:30
(Duplicate of #309)

This is unfortunately a [known issue](https://github.com/joeyespo/grip#known-issues). It's in GitHub's hands now.

Feel free to comment on [the related GitHub issue](https://github.com/isaacs/github/issues/309) to show that people care about this. (You should also probably send an email to support@github.com, as indicated on that repo's [Readme](https://github.com/isaacs/github).)

**Closed by joeyespo** 2015-04-01 19:30 UTC
Labels: duplicate
