### ISSUE TITLE
# inside code block rendered as headings

### ISSUE THREAD

**Issue by wilsonmar** [joeyespo/grip#158] opened 2016-01-01 12:35 UTC
\# is used to prefix headings within github markup text.
\# is also used as comments within some programming code.
Insert a set of 3 back-quotes to enclose source code.
Add # text within the code block.
Desired behavior is # should not be rendered as headings within code blocks.

**Comment by joeyespo** [comment] 2016-02-14 19:32
I'm not able to reproduce.

#### README.md

    # Testing
    
    Testing #158.
    
    ```
    # Example Python code
    
    print('testing!')
    ```

#### Version

```
$ grip -V
Grip 4.1.0
```

#### Command

```
$ grip
 * Running on http://localhost:6419/ (Press CTRL+C to quit)
```

#### Renders as

![output](https://cloud.githubusercontent.com/assets/634573/13035874/ae39eece-d327-11e5-9866-e9005fab6631.png)

Could you show me something similar?

**Comment by joeyespo** [comment] 2016-04-13 04:32
Closing this since I couldn't reproduce.

Also v4.2.0 was just published, if that helps. Upgrade with `pip install --upgrade grip`.

Feel free to re-open with some more details if you're still having a problem.

**Closed by joeyespo** 2016-04-13 04:32 UTC
