### ISSUE TITLE
Export hangs

### ISSUE THREAD

**Issue by atomgomba** [joeyespo/grip#185] opened 2016-07-04 15:48 UTC
grip hangs when trying to export:

```
$ grip --export portals.md
Exporting to portals.html
^C
^C
^C^C
^C^C
^C^C
```
Even Ctrl-C won't stop the execution. I tried using Python 2.7.12 and 3.5.1 as well. I'm on Ubuntu Xenial.

**Comment by JasonYao** [comment] 2016-07-05 03:21
Duplicate of #182, which was patched with #184, though not to my knowledge pushed to pypi. To fix it, try compiling from the latest source, and then post here again if it doesn't work

**Comment by atomgomba** [comment] 2016-07-05 19:07
Thank you very much for the quick response! Cloning the latest master and installing it via setup.py eliminated the issue. If you have some time to look at Tornado web server I think it worth it. It has a templating system without additional dependencies and I'm using it in like a dozen of projects and never ran into backwards compatibility issues. Once again, thanks!

**Comment by joeyespo** [comment] 2016-07-19 07:56
v4.3.0 was just published with a fix. Be sure to run `pip install --upgrade grip`.

Tornado seems good too. Flask has been solid for me in other projects though, and I still really enjoy it. It's more likely my misuse of it that led to this issue. Cheers!

**Closed by joeyespo** 2016-07-19 07:56 UTC
