### ISSUE TITLE
Consider equally recognizing lowercased readme.md files

### ISSUE THREAD

**Issue by matanster** [joeyespo/grip#144] opened 2015-10-24 03:06 UTC
Consider equally recognizing lowercased `readme.md` files, to avoid `Error: No README found at .` when the file is named `readme.md` (lowercase). Github respects lowercase-named readme files, so maybe this makes sense, especially given there's not always a real reason for readme files to be screaming-uppercase.

**Comment by joeyespo** [comment] 2015-11-19 07:38
I'm surprised nobody's opened an issue before you did. This should be fixed in v4.0.0.

Upgrade with `pip install --upgrade grip` and feel free to re-open if you're still having a problem.

Thanks for the issue, @matanster!

**Closed** 2015-11-19 07:38 UTC
Labels: bug

**Comment by Taranchul** [comment] 2020-06-11 21:15
Sorry for commenting on this old topic, but I still get an "Error: No README found at ." on Kubuntu 18.04 with grip version Grip 4.2.0.

**Comment by devfaulter** [comment] 2020-08-19 12:12
I can confirm that I also see this error after installing grip (version 4.2.0-3) on Ubuntu 18.04.5. In my case grip was installed with apt not pip.

**Comment by PJaros** [comment] 2020-10-03 09:28
```
madmike@desktop:~$ python3 -m pip install --upgrade --user pip
Collecting pip
  Using cached pip-20.2.3-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.2
    Uninstalling pip-20.2.2:
      Successfully uninstalled pip-20.2.2
Successfully installed pip-20.2.3
madmike@desktop:~$ python3 -m pip install grip
Defaulting to user installation because normal site-packages is not writeable
Collecting grip
  Using cached grip-4.5.2.tar.gz (145 kB)
Collecting Flask>=0.10.1
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting Markdown>=2.5.1
  Using cached Markdown-3.2.2-py3-none-any.whl (88 kB)
Requirement already satisfied: Pygments>=1.6 in /usr/lib/python3/dist-packages (from grip) (2.2.0)
Collecting docopt>=0.4.0
  Downloading docopt-0.6.2.tar.gz (25 kB)
Collecting path-and-address>=2.0.1
  Using cached path-and-address-2.0.1.zip (6.5 kB)
Requirement already satisfied: requests>=2.4.1 in /usr/lib/python3/dist-packages (from grip) (2.18.4)
Collecting itsdangerous>=0.24
  Using cached itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Jinja2>=2.10.1
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting click>=5.1
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting Werkzeug>=0.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting importlib-metadata; python_version < "3.8"
  Downloading importlib_metadata-2.0.0-py2.py3-none-any.whl (31 kB)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from Jinja2>=2.10.1->Flask>=0.10.1->grip) (1.0)
Collecting zipp>=0.5
  Downloading zipp-3.2.0-py3-none-any.whl (5.1 kB)
Building wheels for collected packages: grip, docopt, path-and-address
  Building wheel for grip (setup.py) ... done
  Created wheel for grip: filename=grip-4.5.2-py3-none-any.whl size=136502 sha256=38d1a33a91996e2a54498ee5032d1ee7f02d18d05e94248259900b249d19734b
  Stored in directory: /home/madmike/.cache/pip/wheels/06/ac/1f/6f39c10baff5c59047719c27c0243d3efcf43bb36cb7b4ffc6
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=19852 sha256=db2b5009834c3be9aab2721b933b67e188575db58b5c9183a68c523f283fb8e1
  Stored in directory: /home/madmike/.cache/pip/wheels/3f/2a/fa/4d7a888e69774d5e6e855d190a8a51b357d77cc05eb1c097c9
  Building wheel for path-and-address (setup.py) ... done
  Created wheel for path-and-address: filename=path_and_address-2.0.1-py3-none-any.whl size=3576 sha256=95ee7dee60361649e728142004422cb519ec2a0a5c7b2019d40a2244de0eb538
  Stored in directory: /home/madmike/.cache/pip/wheels/df/e3/97/63e01a64fec71a71fd8234bfda8c043f49349741c95b977ecd
Successfully built grip docopt path-and-address
Installing collected packages: itsdangerous, Jinja2, click, Werkzeug, Flask, zipp, importlib-metadata, Markdown, docopt, path-and-address, grip
Successfully installed Flask-1.1.2 Jinja2-2.11.2 Markdown-3.2.2 Werkzeug-1.0.1 click-7.1.2 docopt-0.6.2 grip-4.5.2 importlib-metadata-2.0.0 itsdangerous-1.1.0 path-and-address-2.0.1 zipp-3.2.0
madmike@desktop:~$ hash -r
madmike@desktop:~$ grip
Error: No README found at .
```

**Comment by stas00** [comment] 2020-10-31 18:15
Make sure you actually pass a filename `grip somefile.md`. I have just encountered the same while trying to make `grip` to run.

The problem is that `grip` assumes that if you don't pass a filename it thinks you want `README.md` - so currently it emits this not a very user-friendly error. It should probably say something like: `no specific .md file was passed and the default ./README.md hasn't been found` or something like that.
