### ISSUE TITLE
Errno

### ISSUE THREAD

**Issue by foxman209** [joeyespo/grip#268] opened 2018-04-05 04:55 UTC
when I grip，it show me :
[Errno 8] nodename nor servname provided, or not known

**Comment by joeyespo** [comment] 2018-06-02 00:52
I wonder if this is caused by utilizing `localhost` for generating a random port, from

```py
        if port == 0 and open_browser:
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.bind(('localhost', 0))
            port = sock.getsockname()[1]
            sock.close()
```

[This](https://stackoverflow.com/questions/45747730/error-nodename-nor-servname-provided-or-not-known-python-sockets) and [https://stackoverflow.com/questions/39970606/gaierror-errno-8-nodename-nor-servname-provided-or-not-known-with-macos-sie](this) hints at that.

Are you running with port `0` and `--browser` by chance? If not, could you post the exact command you used and the full output (if there's any more).

Thanks!

**Comment by BenGitsCode** [comment] 2018-06-15 17:55
Similar problem here. 

```sh
❯ grip report-data-source.md
 * Using personal access token
Error: [Errno 8] nodename nor servname provided, or not known

forge/notes/shadows/jono-mentor git/master*
❯ grip -b report-data-source.md
 * Using personal access token
Error: [Errno 8] nodename nor servname provided, or not known

forge/notes/shadows/jono-mentor git/master*
❯ zsh --version \n; python --version \n ; brew list --versions grip
zsh 5.3 (x86_64-apple-darwin17.0)
Python 2.7.15
grip 4.5.2
```

my `~/.grip/settings.py` is just my username and personal access token. This is a new grip instance on my work computer, I'll chekc my home computer tonight to see if that's also having the issue.

**Comment by BenGitsCode** [comment] 2018-06-21 13:02
Has anyone gotten beyond this error before? I'm happy to try some further debugging but I'm not sure where to start with this.

**Comment by nikvdp** [comment] 2018-12-13 01:06
@BenGitsCode I had the same issue start happening all of a sudden, after some digging realized that I'd misconfigured my `/etc/hosts` file and deleted this line: 

```
127.0.0.1     localhost
```

Adding that line back into `/etc/hosts` made `grip` start working correctly again.

**Comment by joeyespo** [comment] 2019-06-17 05:04
Hi, all. Is this still happening? If so, can you try @nikvdp's [suggestion](https://github.com/joeyespo/grip/issues/268#issuecomment-446804220)?

I can't reproduce, so I'm closing for now. Feel free to re-open if that doesn't work.

**Closed by joeyespo** 2019-06-17 05:04 UTC
