### ISSUE TITLE
Add live-reload on file edit

### ISSUE THREAD

**Issue by rzajac** [joeyespo/grip#147] opened 2015-11-12 14:35 UTC
Like in the title.

**Comment by joeyespo** [comment] 2015-11-19 06:38
This is now implemented as of version 4.0.0 :smile: Credit goes to @markbt in #135.

Upgrade with `pip install --upgrade grip`.

**Comment by joeyespo** [comment] 2015-11-19 06:40
(For documentation, this is a duplicate of #19.)

**Closed by joeyespo** 2015-11-19 06:40 UTC
