### ISSUE TITLE
grip with virtualenv

### ISSUE THREAD

**Issue by Katsuya-Tomioka** [joeyespo/grip#180] opened 2016-06-23 21:13 UTC
I'm trying to use grip with virtualenv on Mac and Linux with python 2.7. In both cases, grip seems to get stuck somehow. Command line "grip --export" or API (grip.main) doesn't seem to make any difference.  Any suggestion?

**Comment by JasonYao** [comment] 2016-06-26 08:20
@Katsuya-Tomioka 
Can you clarify what you mean when you say

> grip seems to get stuck somehow

Also, when you say

> Command line "grip --export" or API (grip.main) doesn't seem to make any difference.

Do you mean to say that using the command generates an HTML file that appears to be incorrectly formatted for you, or that an HTML file is not generated at all, or that the command simply makes your computer hang, etc.

I'm running on osx 10.11.5 with the latest grip installed and working in two separate virtualenvs via homebrew's [pyenv](https://github.com/yyuu/pyenv) with the [pyenv-virtualenv](https://github.com/yyuu/pyenv-virtualenv) plugin. Grip appears to be working in both 2.7.11 and 3.5.1 for me, so it may be a possible issue during your installation?

**Comment by Katsuya-Tomioka** [comment] 2016-06-28 21:43
No html is written at all. I can't kill it with ctrl-c either. Looking at
trace, the flask app seems to be waiting for input.

I'm osx 10.11.5, and python 2.7.9.

centos6  and python 2.6.6 has the same issue.

**Comment by JasonYao** [comment] 2016-06-29 03:02
So I'm testing the two python versions you listed, both 2.7.9 and 2.6.6.

## Replication Steps
```sh
# Installs testing envs
pyenv install 2.7.9
pyenv install 2.6.6
pyenv virtualenv 2.7.9 grip-test-2.7.9
pyenv virtualenv 2.6.6 grip-test-2.6.6

## Tests (we use the grip README.md for testing)
wget https://raw.githubusercontent.com/yyuu/pyenv-virtualenv/master/README.md -O test.md
pyenv global grip-test-2.7.9
pip install grip
grip test.md

pyenv global grip-test-2.6.6
pip install grip
grip test.md
```

## Results
Both envs worked perfectly fine, and the result could be seen at http://localhost:6419/. Since fresh clean installs appear to be working, I'd just recommend cleaning your system, and re-installing the envs and grip again.

If you don't want to do that, and prefer to just debug the current issues, can you paste which dependencies you have installed? You can do that with a `pip freeze` command, and try and see if there are any outdated dependencies that you could update if that's a possible issue.

## Working grip depencies
### 2.7.9
```
click==6.6
docopt==0.6.2
Flask==0.11.1
grip==4.2.0
itsdangerous==0.24
Jinja2==2.8
Markdown==2.6.6
MarkupSafe==0.23
path-and-address==1.1.0
Pygments==2.1.3
requests==2.10.0
Werkzeug==0.11.10
```

### 2.6.6
```
argparse==1.4.0
click==6.6
docopt==0.6.2
Flask==0.11.1
grip==4.2.0
itsdangerous==0.24
Jinja2==2.8
Markdown==2.6.6
MarkupSafe==0.23
path-and-address==1.1.0
Pygments==2.1.3
requests==2.10.0
Werkzeug==0.11.10
```

![2 6 6 grip test](https://cloud.githubusercontent.com/assets/3739191/16439167/8af01214-3de8-11e6-99ea-190dbc73cd13.png)
![2 7 9 grip test](https://cloud.githubusercontent.com/assets/3739191/16439168/8af190d0-3de8-11e6-9b40-dbfbc064c0c5.png)

**Comment by Katsuya-Tomioka** [comment] 2016-06-29 19:59
Looks like I have the same dependencies. Does "--export" work in your test?

**Comment by JasonYao** [comment] 2016-06-30 03:01
Hmm looks like there's an issue with the `--export` command - I'm getting a hang just like you are, and it can't be killed with a `CTRL` + `C`

## Reproduction steps
```sh
wget https://raw.githubusercontent.com/yyuu/pyenv-virtualenv/master/README.md -O test.md

# Tests virtualenvs 2.6.6, 2.7.9, 2.7.11, 3.5.1
pyenv global grip-test-2.6.6
grip --export test.md

pyenv global grip-test-2.7.9
grip --export test.md

pyenv global grip-test-3.5.1
grip --export test.md

pyenv global grip-test-2.7.11
grip --export test.md

# Tests full python versions
pyenv global 2.7.11
grip --export test.md

pyenv global 3.5.1
grip --export test.md
```

## Results
```sh
# For all versions running the --export command
Exporting to test.html
# Blank line and a deadlock
```
In all cases, just using `grip test.md` worked perfectly, and managed to be displayed fine. However, it looks like the `--export` command is messed up, and causes it to hang waiting for input.

I'd recommend just using the normal `grip filename.md` command for now until this is fixed.

**Comment by joeyespo** [comment] 2016-07-01 05:04
Fixed with #184.

Thanks for getting the conversation going, @Katsuya-Tomioka, and for digging much deeper, @JasonYao! I'll create a new release with the fix shortly.

**Closed by joeyespo** 2016-07-01 05:04 UTC

**Comment by Katsuya-Tomioka** [comment] 2016-07-05 13:43
Master works great. (python 2.7.9 on mac 10.11.5 and python 2.6.6 on centos6) Thanks for your help.

**Comment by joeyespo** [comment] 2016-07-19 07:45
v4.3.0 was just published. Run `pip install --upgrade grip` to get the fix without running off `master`.

Thanks for being patient in the meantime :smiley:
